{
 "title": "P360 App Resources",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(kube_node_info, node)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "deployment",
    "label": "Deployments",
    "query": "label_values(kube_deployment_metadata_generation{namespace=~\"$namespace\"}, deployment)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{namespace=~\"$namespace\", node=~\"$node\", created_by_name=~\"$deployment-\\\\w{5,10}\"}, pod)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(kube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}, container)"
   }
  ]
 },
 "panels": [
  {
   "title": "Resources",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod!=\"\", container!=\"\", container!=\"POD\"} * on(pod) group_left() kube_pod_info{namespace=~\"$namespace\", node=~\"$node\"}) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod!=\"\", image!=\"\", container!=\"POD\"}[5m]) * on(pod) group_left() kube_pod_info{namespace=~\"$namespace\", node=~\"$node\"}) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod!=\"\"}[5m]) * on(pod) group_left() kube_pod_info{namespace=~\"$namespace\", node=~\"$node\"}) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", pod!=\"\"}) by (pod) or sum(kube_pod_container_resource_limits_memory_bytes{pod!=\"\"}) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", pod!=\"\"}) by (pod) or sum(kube_pod_container_resource_limits_cpu_cores{pod!=\"\"}) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(kube_pod_info{namespace=~\"$namespace\", node=~\"$node\"}) by (pod, node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_usage_bytes{pod=~\"$pod\", container=~\"$container\", container!=\"POD\", container!=\"\"})",
     "legendFormat": "Current"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", pod=~\"$pod\", container=~\"$container\"}) or sum(kube_pod_container_resource_limits_memory_bytes{pod=~\"$pod\", container=~\"$container\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{image!=\"\",container!=\"POD\",pod=~\"$pod\", container=~\"$container\"}[5m]))",
     "legendFormat": "Current"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", pod=~\"$pod\", container=~\"$container\"}) or sum(kube_pod_container_resource_limits_cpu_cores{pod=~\"$pod\", container=~\"$container\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (rate(container_network_receive_bytes_total{pod=~\"$pod\"}[5m]))",
     "legendFormat": "Network I/O"
    }
   ]
  }
 ]
}